service: mypitch

provider:
  name: aws
  stage: beta
  region: us-east-1
  runtime: python3.6

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  simple:
    name: musicsinmypitch
    handler: handler.musicsinmypitch
    events:
      - http:
          path: /musicsinmypitch
          method: GET
